application: fbbcfaab60da26f9b38f38fa658910
#application: personal-financial-140007
version: 1
runtime: go
api_version: go1

handlers:
- url: /.*
  script: _go_app
env_variables:
  BUCKET_NAME:  www.rc-greed.com